<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-LKHQBG4" failures="4" tests="4" name="Test(failed)" time="0.084" errors="0" timestamp="2023-02-10T11:04:46 IST">
  <testcase classname="testng.learning.ArithmeticOpertion" name="divTwoNo" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [10] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [5]
at testng.learning.ArithmeticOpertion.divTwoNo(ArithmeticOpertion.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- divTwoNo -->
  <testcase classname="testng.learning.ArithmeticOpertion" name="mulTwoNo" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [20] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [20] but found [10]
at testng.learning.ArithmeticOpertion.mulTwoNo(ArithmeticOpertion.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- mulTwoNo -->
  <testcase classname="testng.learning.ArithmeticOpertion" name="subTwoNo" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [6] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [4]
at testng.learning.ArithmeticOpertion.subTwoNo(ArithmeticOpertion.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- subTwoNo -->
  <testcase classname="testng.learning.ArithmeticOpertion" name="sumThreeNo" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [5] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [10]
at testng.learning.ArithmeticOpertion.sumThreeNo(ArithmeticOpertion.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- sumThreeNo -->
  <testcase classname="testng.learning.ArithmeticOpertion" name="sumTwoNo" time="0.0">
    <ignored/>
  </testcase> <!-- sumTwoNo -->
  <testcase classname="testng.learning.ArithmeticOpertion" name="divThreeNo" time="0.0">
    <ignored/>
  </testcase> <!-- divThreeNo -->
  <testcase classname="testng.learning.ArithmeticOpertion" name="subThreeNo" time="0.0">
    <ignored/>
  </testcase> <!-- subThreeNo -->
  <testcase classname="testng.learning.ArithmeticOpertion" name="mulThreeNo" time="0.0">
    <ignored/>
  </testcase> <!-- mulThreeNo -->
</testsuite> <!-- Test(failed) -->
